### ISSUE TITLE
请问下怎么添加umi插件

### ISSUE THREAD

**Issue by Kevin9703** [porosjs/poros#1]
我用npx umi g tailwindcss添加tailwindcss后启动报错
info  - Poros v1.1.5
fatal - Error: Cannot find module '../renderer/pages/Home' from '/Users/xmly/Desktop/study/myapp/src/renderer/pages'
    at Function.resolveSync [as sync] (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/utils/compiled/resolve/index.js:1:12304)
    at Object.onResolveComponent (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/preset-umi/dist/features/tmpFiles/routes.js:71:32)
    at transformRoute (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/core/dist/route/routesConfig.js:72:44)
    at /Users/xmly/Desktop/study/myapp/node_modules/@umijs/core/dist/route/routesConfig.js:48:5
    at Array.forEach (<anonymous>)
    at transformRoutes (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/core/dist/route/routesConfig.js:47:15)
    at getConfigRoutes (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/core/dist/route/routesConfig.js:38:3)
    at Proxy.getRoutes (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/preset-umi/dist/features/tmpFiles/routes.js:61:46)
    at Hook.fn (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/preset-umi/dist/features/appData/appData.js:51:35)
    at /Users/xmly/Desktop/study/myapp/node_modules/@umijs/core/dist/service/service.js:136:38
    at eval (eval at create (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:8410), <anonymous>:84:17)
    at new Promise (<anonymous>)
    at Hook.eval [as promise] (eval at create (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:8410), <anonymous>:6:8)
    at Hook.PROMISE_DELEGATE [as _promise] (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:4959)
    at Service.applyPlugins (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/core/dist/service/service.js:145:24)
    at Service.run (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/core/dist/service/service.js:290:31) {
  code: 'MODULE_NOT_FOUND'
}
fatal - A complete log of this run can be found in:
fatal - /Users/xmly/Desktop/study/myapp/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues

请问要怎么正确添加umi插件呢

**Comment by Kevin9703** [comment]
![image](https://github.com/porosjs/poros/assets/51311316/c4a0baaa-ef5f-463b-95d2-b43a82217d7e)
然后我改了routes，又报错
✘ [ERROR] Can't resolve '/Users/xmly/Desktop/study/myapp/src/pages/Home/index.tsx' in '/Users/xmly/Desktop/study/myapp/src/.poros/core' [plugin esbuildAliasPlugin]

    node_modules/enhanced-resolve/lib/Resolver.js:309:17:
      309 │       const error = new Error("Can't " + message);
          ╵                     ^

    at finishWithoutResolve (/Users/xmly/Desktop/study/myapp/node_modules/enhanced-resolve/lib/Resolver.js:309:18)
    at /Users/xmly/Desktop/study/myapp/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /Users/xmly/Desktop/study/myapp/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/xmly/Desktop/study/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/xmly/Desktop/study/myapp/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/xmly/Desktop/study/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/xmly/Desktop/study/myapp/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/xmly/Desktop/study/myapp/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/xmly/Desktop/study/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/xmly/Desktop/study/myapp/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/xmly/Desktop/study/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/xmly/Desktop/study/myapp/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/xmly/Desktop/study/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/xmly/Desktop/study/myapp/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/xmly/Desktop/study/myapp/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/xmly/Desktop/study/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/xmly/Desktop/study/myapp/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/xmly/Desktop/study/myapp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/xmly/Desktop/study/myapp/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:41:15
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

  This error came from the "onResolve" callback registered here:

    node_modules/@umijs/preset-umi/dist/features/prepare/esbuildPlugins/esbuildAliasPlugin.js:89:16:
      89 │           build.onResolve({ filter: filter2 }, async (args) => {
         ╵                 ~~~~~~~~~

    at /Users/xmly/Desktop/study/myapp/node_modules/@umijs/preset-umi/dist/features/prepare/esbuildPlugins/esbuildAliasPlugin.js:89:17
    at Array.forEach (<anonymous>)
    at setup (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/preset-umi/dist/features/prepare/esbuildPlugins/esbuildAliasPlugin.js:75:10)
    at handlePlugins (/Users/xmly/Desktop/study/myapp/node_modules/esbuild/lib/main.js:1279:21)
    at buildOrContextImpl (/Users/xmly/Desktop/study/myapp/node_modules/esbuild/lib/main.js:968:5)
    at Object.buildOrContext (/Users/xmly/Desktop/study/myapp/node_modules/esbuild/lib/main.js:776:5)
    at /Users/xmly/Desktop/study/myapp/node_modules/esbuild/lib/main.js:2172:68
    at new Promise (<anonymous>)
    at Object.context (/Users/xmly/Desktop/study/myapp/node_modules/esbuild/lib/main.js:2172:27)
    at Object.context (/Users/xmly/Desktop/study/myapp/node_modules/esbuild/lib/main.js:2012:58)
    at build (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/preset-umi/dist/features/prepare/build.js:91:46)
    at Hook.fn (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/preset-umi/dist/features/prepare/prepare.js:105:40)
    at /Users/xmly/Desktop/study/myapp/node_modules/@umijs/core/dist/service/service.js:184:15

  The plugin "esbuildAliasPlugin" was triggered by this import

    src/.poros/core/route.tsx:12:69:
      12 │ '2': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
         ╵                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~

fatal - Error: Build failed with 1 error:
node_modules/enhanced-resolve/lib/Resolver.js:309:17: ERROR: [plugin: esbuildAliasPlugin] Can't resolve '/Users/xmly/Desktop/study/myapp/src/pages/Home/index.tsx' in '/Users/xmly/Desktop/study/myapp/src/.poros/core'
    at failureErrorWithLog (/Users/xmly/Desktop/study/myapp/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/xmly/Desktop/study/myapp/node_modules/esbuild/lib/main.js:1048:25
    at /Users/xmly/Desktop/study/myapp/node_modules/esbuild/lib/main.js:1512:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errors: [
    {
      detail: [Error],
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: 'esbuildAliasPlugin',
      text: "Can't resolve '/Users/xmly/Desktop/study/myapp/src/pages/Home/index.tsx' in '/Users/xmly/Desktop/study/myapp/src/.poros/core'"
    }
  ],
  warnings: []
}
fatal - A complete log of this run can be found in:
fatal - /Users/xmly/Desktop/study/myapp/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues

**Comment by WangJM001** [comment]
是要使用tailwind是么？可以支持的，在路上，晚点给你回复

**Comment by WangJM001** [comment]
umi原有命令需要使用poros替换，比如：npx poros g tailwindcss

版本：v1.1.5
命令：npx poros g tailwindcss
系统：MacOS
npmClient：pnpm

我测试是OK! 在添加tailwind之前demo能正常运行么？

另外正常来说执行`npx umi g tailwindcss`会报错（umi: command not found），看你报错的信息像是框架对umi的补丁没打上，可以尝试下删除umi g tailwindcss 生成的文件，删除node_modules和lock文件重新install，再执行`npx poros g tailwindcss`, 如果还是不行尝试手动执行下补丁`node node_modules/poros/scripts/postinstall.js`

正确的生成tailwind.config.js内容应该是：
```js
module.exports = {
  content: [
    './src/renderer/pages/**/*.tsx',
    './src/renderer/components/**/*.tsx',
    './src/renderer/layouts/**/*.tsx'
  ],
}
```

<img width="921" alt="CleanShot 2024-06-19 at 19 33 18@2x" src="https://github.com/porosjs/poros/assets/20501316/2cc7ec0b-4c8e-4349-8179-8f7d12597ba1">

**Comment by Kevin9703** [comment]
按照大佬的方法试了一下，执行`npx poros g tailwindcss`，然后会报错（我不知道为啥我贴图长传然后不会展示图😭）

error - Error: Cannot find module '../renderer/pages/Home' from '/Users/xmly/Desktop/study/myapp/src/renderer/pages'
    at Function.resolveSync [as sync] (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/utils/compiled/resolve/index.js:1:12304)
    at Object.onResolveComponent (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/preset-umi/dist/features/tmpFiles/routes.js:71:32)
    at transformRoute (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/core/dist/route/routesConfig.js:72:44)
    at /Users/xmly/Desktop/study/myapp/node_modules/@umijs/core/dist/route/routesConfig.js:48:5
    at Array.forEach (<anonymous>)
    at transformRoutes (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/core/dist/route/routesConfig.js:47:15)
    at getConfigRoutes (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/core/dist/route/routesConfig.js:38:3)
    at Proxy.getRoutes (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/preset-umi/dist/features/tmpFiles/routes.js:61:46)
    at Hook.fn (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/preset-umi/dist/features/appData/appData.js:51:35)
    at /Users/xmly/Desktop/study/myapp/node_modules/@umijs/core/dist/service/service.js:136:38
    at eval (eval at create (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:8410), <anonymous>:67:17)
    at new Promise (<anonymous>)
    at Hook.eval [as promise] (eval at create (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:8410), <anonymous>:6:8)
    at Hook.PROMISE_DELEGATE [as _promise] (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:4959)
    at Service.applyPlugins (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/core/dist/service/service.js:145:24)
    at Service.run (/Users/xmly/Desktop/study/myapp/node_modules/@umijs/core/dist/service/service.js:290:31) {
  code: 'MODULE_NOT_FOUND'
}
fatal - A complete log of this run can be found in:
fatal - /Users/xmly/Desktop/study/myapp/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
error Command failed with exit code 1.

之后执行了`node node_modules/poros/scripts/postinstall.js`
就能正常启动啦！🎉

感谢大佬的回复！
偶然看到这个框架，立马试了一下，很好用方便，感谢大佬！

**Comment by WangJM001** [comment]
因为框架魔改了umi的一些代码，应该是安装时postinstall的脚本没正常执行。
框架刚迭代不久，主要是自己公司项目在使用，可能会有些问题，随时沟通😊！

你用的啥子系统？window?macOS?linux?
npmClient用的啥？yarn？npm？pnpm？
我本地测试下看看根本问题出在哪里，为啥postinstall没执行

**Comment by Kevin9703** [comment]
系统：macOS
npmClient：yarn
我是直接新创建了项目，启动正常，然后执行`npx poros g tailwindcss`的
目前公司刚好有个项目需要electron，我后面有时间的话学习一下大佬的代码，看看能不能贡献一点😁

**Comment by WangJM001** [comment]
ok😊

**Comment by WangJM001** [comment]
使用yarn的话，在添加包后就会出问题，可以修改package.json->scripts解决：
"postinstall": "node node_modules/poros/scripts/postinstall.js & poros setup"，
下个版本会更新修复
